site_name: PyAutomation Documentation
site_url: https://pyautomation.readthedocs.io/
repo_name: PyAutomation
repo_url: https://github.com/know-ai/PyAutomation
edit_uri: ""

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Summary: "index.md"
  - Architecture: "architecture.md"
  - Setup: "setup.md"
  - User Guide:
      - Summary: "Users_Guide/index.md"
      - Database:
          - Summary: "Users_Guide/Database/index.md"
      - Communications:
          - Summary: "Users_Guide/Communications/index.md"
      - Tags:
          - Summary: "Users_Guide/Tags/index.md"
          - Create Tag: "Users_Guide/Tags/Create.md"
          - Update Tag: "Users_Guide/Tags/Update.md"
          - Delete Tag: "Users_Guide/Tags/Delete.md"
          - Trends: "Users_Guide/Tags/Trends.md"
      - Alarms:
          - Summary: "Users_Guide/Alarms/index.md"
      - Users:
          - Summary: "Users_Guide/Users/index.md"
      - Settings:
          - Summary: "Users_Guide/Settings/index.md"
  - Developer Guide:
      - Summary: "Developments_Guide/index.md"
      - Creating Diagrams: "Developments_Guide/diagrams.md"
      - Core Concepts:
          - Summary: "Developments_Guide/core/index.md"
          - Alarms: "Developments_Guide/core/alarms.md"
          - CVT: "Developments_Guide/core/cvt.md"
          - Data Logger: "Developments_Guide/core/datalogger.md"
          - State Machines: "Developments_Guide/core/state_machines.md"
      - IIoT:
          - Summary: "Developments_Guide/iiot/index.md"
          - Modbus: "Developments_Guide/iiot/modbus.md"
          - OPC UA: "Developments_Guide/iiot/opcua.md"
      - API Reference:
          - Summary: "Developments_Guide/API/index.md"
          - Core: "Developments_Guide/API/core.md"
          - Events: "Developments_Guide/API/events.md"
          - Users: "Developments_Guide/API/users.md"
          - Settings: "Developments_Guide/API/settings.md"
          - Authorization: "Developments_Guide/API/authorization.md"
          - Alarms:
              - Summary: "Developments_Guide/API/alarms/index.md"
              - Alarm: "Developments_Guide/API/alarms/alarm.md"
              - States: "Developments_Guide/API/alarms/states.md"
              - Triggers: "Developments_Guide/API/alarms/triggers.md"
          - State Machines:
              - Summary: Developments_Guide/API/state_machine/index.md
              - Automation State Machine: Developments_Guide/API/state_machine/automation_state_machine.md
              - Machine: Developments_Guide/API/state_machine/machine.md
          - CVT:
              - Summary: "Developments_Guide/API/cvt/index.md"
              - Variables: "Developments_Guide/API/cvt/variables.md"
              - CVTEngine: "Developments_Guide/API/cvt/cvt_engine.md"
              - CVT: "Developments_Guide/API/cvt/cvt.md"
          - Managers:
              - Summary: Developments_Guide/API/managers/index.md
              - Alarm Manager: "Developments_Guide/API/managers/alarm_manager.md"
              - DB Manager: Developments_Guide/API/managers/db.md
              - OPC UA Client: "Developments_Guide/API/managers/opcua_client.md"
              - State Machine: Developments_Guide/API/managers/state_machine.md
          - Workers:
              - Summary: Developments_Guide/API/workers/index.md
              - State Machine: Developments_Guide/API/workers/state_machine.md
              - Async State Machine: Developments_Guide/API/workers/async_state_machine.md
              - Scheduler Threads: Developments_Guide/API/workers/sched_thread.md
              - Main Scheduler: Developments_Guide/API/workers/main_scheduler.md
              - Base Worker: Developments_Guide/API/workers/worker.md
              - Logger Worker: Developments_Guide/API/workers/logger.md
          - Data Logger:
              - Summary: Developments_Guide/API/datalogger/index.md
              - Data Logger Engine: Developments_Guide/API/datalogger/datalogger_engine.md
              - Data Logger: Developments_Guide/API/datalogger/datalogger.md
          - DB Models:
              - Summary: Developments_Guide/API/db_models/index.md
              - Core: "Developments_Guide/API/db_models/core.md"
              - Alarms: "Developments_Guide/API/db_models/alarms.md"
              - Events: "Developments_Guide/API/db_models/events.md"
              - Logs: "Developments_Guide/API/db_models/logs.md"
              - Machines: "Developments_Guide/API/db_models/machines.md"
              - OPC UA: "Developments_Guide/API/db_models/opcua.md"
              - Tags: Developments_Guide/API/db_models/tags.md
              - Users: "Developments_Guide/API/db_models/users.md"
      - Testing: "Developments_Guide/testing.md"
      - Logs: "Developments_Guide/logs.md"
  - Roadmap: "roadmap.md"
  - Contributions: "CONTRIBUTING.md"

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - mkautodoc

plugins:
  - search

extra_css:
  - css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
