site_name: PyAutomation Documentation

theme:
  name: material

repo_name: PyAutomation
repo_url: https://github.com/know-ai/PyAutomation
edit_uri: ""
site_dir: _build/html

nav:
    - Summary: 'index.md'
    - Architecture: 'architecture.md'
    - User' Guide:
      - Summary: 'Users_Guide/index.md'
      - Alarms: 
        - Summary: 'Users_Guide/Alarms/index.md' 
      - Database:
        - Summary: 'Users_Guide/Database/index.md' 
      - Communications: 
        - Summary: 'Users_Guide/Communications/index.md' 
      - Tags: 
        - Summary: 'Users_Guide/Tags/index.md'   
        - Create Tag: 'Users_Guide/Tags/Create.md' 
        - Update Tag: 'Users_Guide/Tags/Update.md' 
        - Delete Tag: 'Users_Guide/Tags/Delete.md' 
    - Setup: 'setup.md'
    - Development's Guide:
      - Summary: 'Developments_Guide/index.md'
      - Core:
        - Summary: 'Developments_Guide/core/index.md'
        - State Machines: 'Developments_Guide/core/state_machines.md'
        - CVT: 'Developments_Guide/core/cvt.md'
        - DataLogger: 'Developments_Guide/core/datalogger.md'
        - Alarms: 'Developments_Guide/core/alarms.md'
      - Industrial Protocols:
        - Summary: 'Developments_Guide/iiot/index.md'
        - OPCUA: 'Developments_Guide/iiot/opcua.md'
        - Modbus: 'Developments_Guide/iiot/modbus.md'
      - Logs: 'Developments_Guide/logs.md'
      - Testing: 'Developments_Guide/testing.md'
      - API:
        - Summary: 'Developments_Guide/API/index.md'
        - Core: 'Developments_Guide/API/core.md'
        - State Machines:
          - Summary: Developments_Guide/API/state_machine/index.md
          - Automation State Machine: Developments_Guide/API/state_machine/automation_state_machine.md
          - Leak State Machine: Developments_Guide/API/state_machine/leak_state_machine.md
          - Machine: Developments_Guide/API/state_machine/machine.md
        - CVT:
          - Summary: 'Developments_Guide/API/cvt/index.md'
          - CVTEngine: 'Developments_Guide/API/cvt/cvt_engine.md'
          - CVT: 'Developments_Guide/API/cvt/cvt.md'
        - Data Logger:
          - Summary: Developments_Guide/API/datalogger/index.md
          - Data Logger Engine: Developments_Guide/API/datalogger/datalogger_engine.md
          - Data Logger: Developments_Guide/API/datalogger/datalogger.md
        - Workers:
          - Summary: Developments_Guide/API/workers/index.md
          - State Machine: Developments_Guide/API/workers/state_machine.md
          - Async State Machine: Developments_Guide/API/workers/async_state_machine.md
          - Scheduler Threads: Developments_Guide/API/workers/sched_thread.md
          - Main Scheduler: Developments_Guide/API/workers/main_scheduler.md
        - Managers:
          - Summary: Developments_Guide/API/managers/index.md
          - State Machine: Developments_Guide/API/managers/state_machine.md
          - DB: Developments_Guide/API/managers/db.md
        - DB Models:
          - Summary: Developments_Guide/API/db_models/index.md
          - Tags: Developments_Guide/API/db_models/tags.md
    - Integration's Guide:
      - Summary: 'Integrations_Guide/index.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - pymdownx.arithmatex:
      generic: true

extra_css:
    - css/custom.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js